Write a NumPy program to test whether none of the elements of a given array is zero

In [6]:
import numpy as np

In [7]:
given_array = np.random.randint(0,100,(5,6))
print(given_array)

[[49 67 41 48 13 45]
 [96 73 86 40 23 98]
 [12 95 87 89 11 85]
 [62 77 47 37 33 74]
 [70  0 68 33  5 71]]


In [8]:
np.all(given_array)

False

In [9]:
(given_array != 0).all()

False

Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [10]:
given_array = np.random.randint(0,100, (6,4))

In [11]:
np.any(given_array)

True

Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).

In [12]:
given_array = np.random.randint(1,87,(6,7))

In [13]:
np.isfinite(given_array).all()

True

In [14]:
given_array = np.array([1 , 644, np.nan , np.inf])

In [15]:
np.isfinite(given_array).all()

False

Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).

In [16]:
given_array = np.array([1,5,np.inf , np.nan])

In [17]:
np.isfinite(given_array)
#isnan to check "not a number"
#isinf to check infinte values
#iscomplex , isreal , isscalar, isinf, isnan

array([ True,  True, False, False])

Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.<br> #Solution pending