Write a NumPy program to test whether none of the elements of a given array is zero

In [2]:
import numpy as np

In [18]:
given_array = np.random.randint(0,100,(5,6))
print(given_array)

[[73 53 68 48 27  4]
 [27 84 45 69 13 84]
 [ 4 95 45 90 97 67]
 [20 95 10 63  7 13]
 [16 91  2 62 15 93]]


In [16]:
np.all(given_array)

False

In [19]:
(given_array != 0).all()

True

Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [20]:
given_array = np.random.randint(0,100, (6,4))

In [21]:
np.any(given_array)

True

Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).

In [22]:
given_array = np.random.randint(1,87,(6,7))

In [25]:
np.isfinite(given_array).all()

True

In [26]:
given_array = np.array([1 , 644, np.nan , np.inf])

In [30]:
np.isfinite(given_array).all()

False

Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).